const mcData = require('minecraft-data')('1.8.9');
module.exports = {
	ENTITIES: {
		'Mesh|Box|{"width":0.99,"height":0.99,"depth":0.99,"diffuseColor":[224,225,255],"emissiveColor":[224,225,255]}': [mcData.entitiesByName.PrimedTnt.id],
		'Mesh|BloxdBlock|{"blockName":"INTERNAL_MESH_Boat","size":1.2,"meshOffset":[0,0,0]}': [mcData.entitiesByName.Boat.id],
		'Arrow': [mcData.entitiesByName.Arrow.id],
		'Pebble': [mcData.entitiesByName.Snowball.id],
		'Reinforced Pebble': [mcData.entitiesByName.Snowball.id],
		'Snowball': [mcData.entitiesByName.Snowball.id],
		'Fireball': [mcData.entitiesByName.Fireball.id],
		'RPG': [mcData.entitiesByName.Fireball.id],
		'Moonstone Orb': [mcData.entitiesByName.ThrownEnderpearl.id],
		'Splash Slowness Potion': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Slowness Potion II': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Poison Potion': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Poison Potion II': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Weakness Potion': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Weakness Potion II': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Instant Damage Potion': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Instant Damage Potion II': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Milk Potion': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Speed Potion': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Speed Potion II': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Defense Potion': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Defense Potion II': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Strength Potion': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Strength Potion II': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Invisibility Potion': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Jump Potion': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Jump Potion II': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Knockback Potion': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Knockback Potion II': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Regeneration Potion': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Regeneration Potion II': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Instant Healing Potion': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Instant Healing Potion II': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Haste Potion': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Haste Potion II': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Shield Potion': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Shield Potion II': [mcData.entitiesByName.ThrownPotion.id],
		'Splash Heat Resistance Potion': [mcData.entitiesByName.ThrownPotion.id],
		'Draugr Skeleton': [mcData.entitiesByName.Skeleton.id, true],
		'Draugr Knight': [mcData.entitiesByName.Zombie.id, true],
		'Draugr Zombie': [mcData.entitiesByName.Zombie.id, true],
		'Frost Skeleton': [mcData.entitiesByName.Skeleton.id, true],
		'Frost Zombie': [mcData.entitiesByName.Zombie.id, true],
		'Frost Golem': [mcData.entitiesByName.Zombie.id, true],
		'Cow': [mcData.entitiesByName.Cow.id, true],
		'Sheep': [mcData.entitiesByName.Sheep.id, true],
		'Pig': [mcData.entitiesByName.Pig.id, true],
		'2': [mcData.entitiesByName.Item.id]
	}
};